config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path

  devise_for :users

  get 'songs/new'

  get 'songs/index'

  get 'songs/upload'

  get 'songs/delete'

  root 'static_pages#home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'dashing/dashboards'

  get 'dashboard' => 'dashing/dashboards'

  resources :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_attached_file :mp3
  validates_attachment_content_type :mp3, content_type: /mp3/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
  end  
end

app/controllers/dashing_controller.rb
class DashingController < ApplicationController
  def dashboard
  end  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def create
    @song = Song.create(song_params)
  end

  def song_params
    params.require(:song).permit!
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @song = Song.new
  end

  def help
  end

  def about
  end

  def dashboard
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashing_helper.rb
module DashingHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dashing/dashboards/sample.html.erb
<% content_for :title do %>
  My super sweet dashboard
<% end %>

<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="welcome" data-view="Text" data-title="Hello" data-text="This is your shiny new dashboard." data-moreinfo="Protip: You can drag the widgets around!"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="synergy" data-view="Meter" data-title="Synergy" data-min="0" data-max="100"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="2">
      <div data-id="buzzwords" data-view="List" data-unordered="true" data-title="Buzzwords" data-moreinfo="# of times said around the office"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="valuation" data-view="Number" data-title="Current Valuation" data-moreinfo="In billions" data-prefix="$"></div>
    </li>

    <li data-row="1" data-col="1" data-sizex="2" data-sizey="1">
      <div data-id="convergence" data-view="Graph" data-title="Convergence" style="background-color:#ff9618"></div>
    </li>
  </ul>
  <center><div style="font-size: 12px">Try this: curl -X PUT 'http://<%= request.host %>:<%= request.port %>/dashing/widgets/welcome' -d "widget[text]=Dashing is awesome"</div></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | ChoreoMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "ChoreoMe", '#', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '#' %></li>
          <li><%= link_to "Help",   '#' %></li>
          <li><%= link_to "About",  '#' %></li>
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Dashboard",  dashboard_path     %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="container">
  <% if notice %>  <div class = "alert alert-info"><%= notice %></div> <% end %>
  <% if alert  %>  <div class = "alert alert-warning"><%= alert %></div><% end %>
    <%= yield %>
  </div>
</body></html>

app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= yield :title %></title>

    <%= javascript_include_tag 'dashing/application' %>
    <%= stylesheet_link_tag 'dashing/application' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="/favicon.ico">
  </head>
  <body>
    <div id="container">
      <%= yield %>
    </div>

    <% if Rails.env.development? %>
      <div id="saving-instructions">
        <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
        <textarea id="gridster-code"></textarea>
      </div>
      <a href="#saving-instructions" id="save-gridster">Save this layout</a>
    <% end %>
  </body>
</html>

app/views/songs/create.html.erb
<%= link_to "My Song", @song.mp3.url %>

app/views/songs/index.html.erb
<table class="table table-striped">
   <thead>
     <tr>
       <th> Song Name</th>
     </tr>
   </thead>

   <tbody>
     <%- Song.all.each do |s| %>
       <tr>
         <td>
          <%= link_to s.mp3_file_name, s.mp3.url %>
         </td>
       </tr>
     <% end %>
   </tbody>
 </table>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>ChoreoMe</h1>

  <h2>
  <%= simple_form_for @song do |f| %>
     <%= f.input :mp3 %>
     <%= f.submit %>
     <% end %>

     <%- Song.all.each do |s| %>
   <audio id="choreo" src="<%= s.mp3.url %>" controls autoplay loop> <p>Your browser does not support the <code>audio</code> element.</p> </audio>
   <div>
     <button type="button" class="btn btn-default glyphicon glyphicon-play" onclick="document.getElementById('choreo').play()"></button>
     <button type="button" class="btn btn-default glyphicon glyphicon-pause" onclick="document.getElementById('choreo').pause()"></button>
     <button type="button" class="btn btn-default glyphicon glyphicon-plus" onclick="document.getElementById('choreo').volume+=0.1"></button>
     <button type="button" class="btn btn-default glyphicon glyphicon-minus" onclick="document.getElementById('choreo').volume-=0.1"></button>
     <button type="button" class="btn btn-default" onclick="document.getElementById('choreo').playbackRate=0.75">.75x</button>
     <button type="button" class="btn btn-default" onclick="document.getElementById('choreo').playbackRate=1">1x</button>
     <button type="button" class="btn btn-default" onclick="document.getElementById('choreo').playbackRate=1.25">1.25x</button>
     <button type="button" class="btn btn-default" onclick="document.getElementById('choreo').playbackRate=0.5">.5x </button>

  <div class="row .text-center">
   <div class="center-block">
    <div class="col-lg-4 col-lg-offset-4">
     <div class="input-group">
       <span class="input-group-btn">
         <button  onclick="document.getElementById('choreo').currentTime=x" class="btn btn-default" type="button">Start at X second</button>
       </span>
       <input type="text" class="form-control" placeholder="Enter the second!">
     </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div>
    <br>
    <br>
     <% end %>
  </h2>